# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  core:
    root: web_deploy/swagger.yaml
    rules:
      operation-summary: warn
      no-enum-type-mismatch: warn

extends:
  - ./node_modules/@vality/redocly-utils/lib/config.yaml
